### ISSUE TITLE
If range is `display: none` on first render, subsequent renders do not work properly

### ISSUE THREAD

**Issue by DaddyWarbucks** [whoisandy/react-rangeslider#42]
I have the `<Slider />` component inside of a modal. This modal has an initial CSS `display: none`. On some state change, a class is added to the modal changing its CSS to `display: block`.

The Slider is initially rendered inside this modal, but the ` this.refs.slider` returns `undefined`. I am assuming this is because `findDOMNode` cannot find hidden nodes? 

When the modal is later shown, the Slider does not have access to what was done in `handleUpdate`. Specifically the state that was set:
```
this.setState({
  limit: sliderPos - handlePos,
  grab: handlePos / 2,
});
```
Therefore, it does not render properly. Unfortunately, I can't just check in the render func: `if (!this.refs.slider) {this.handleUpdate()}` because `this.handleUpdate` touches resets state.

Thanks!

**Comment by whoisandie** [comment]
@DaddyWarbucks Yeah that seems to happen because `display: none` will still mount the component, causing it to mis calculate the bounding rect of slider. IMHO, the probable and the suggested way is to use a conditional check in your render function instead of relying on classes. Below shown is an example of what I exactly mean.

```js
{
                    visible ?
                    (
                        <div className="volume-container">
                            <Volume
                                volume={value}
                                onChange={this.props.change}
                            />
                            <button
                                type="button"
                                onClick={this.handleMute}
                            >
                                {muted ? 'Unmute' : 'Mute'}
                            </button>
                        </div>
                    ) : null
                }
```
