### ISSUE TITLE
Can't run project locally

### ISSUE THREAD

**Issue by kimulus** [whoisandy/react-rangeslider#47]
Just pulled and did a NPM install and NPM start, and I have those errors 

ERROR in ./docs/app.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/***/code/react-rangeslider/lib/index.css in /Users/kimus/code/react-rangeslider/docs
 @ ./docs/app.js 35:0-42

ERROR in ./docs/components/sliders/labels.js
Module not found: Error: Cannot resolve 'file' or 'directory' /Users/***/code/react-rangeslider in /Users/kimus/code/react-rangeslider/docs/components/sliders
 @ ./docs/components/sliders/labels.js 13:24-52

**Comment by manpenaloza** [comment]
had the same issue yesterday.

can be solved temporarily by...
1.) `npm build`
2.) `npm start`

...with the disadvantage that you always have to rebuild after adjusting code in the repo.

**Comment by kimulus** [comment]
I have tried and I still have the same problem,

**Comment by whoisandy** [comment]
9e7ce831752df717c61bf5d3eff5589bcc4522cd fixes the missing files issue.
