### ISSUE TITLE
Support for click & drag behavior

### ISSUE THREAD

**Issue by martinpesout** [whoisandy/react-rangeslider#52]
When I click on fill area, handler is moved to new position. Thant's fine. Problem is that when I'm still having mouse button pressed, I cannot move with handler. The only way how to do it is release mouse button, click on handler again and drag. Is there any chance to add support for this behavior?  

![dub-05-2017 14-54-46](https://cloud.githubusercontent.com/assets/239468/24706415/e04452c6-1a0f-11e7-97e6-5f64a3e4c19b.gif)

**Comment by ramkumarramarajbb** [comment]
@whoisandy Still this behavior not working..
