### ISSUE TITLE
React 15.5 PropTypes Warning

### ISSUE THREAD

**Issue by pieshop** [whoisandy/react-rangeslider#55]
Component is throwing this error:

react.js:3287 Warning: Accessing PropTypes via the main React package is deprecated. Use the prop-types package from npm instead.

Related:
https://facebook.github.io/react/warnings/dont-call-proptypes.html

**Comment by jjojohjohn** [comment]
@whoisandie has this been worked on yet?

**Comment by sorahn** [comment]
Added a PR to use the external PropTypes library.

**Comment by tsheaff** [comment]
@whoisandie any status update on this.  Trying to get my warnings down to zero :)
