### ISSUE TITLE
Minimal example not working

### ISSUE THREAD

**Issue by bigstas** [whoisandy/react-rangeslider#59]
[Now updated: I put the CSS link in.]
I'm writing a web app using Meteor and React and would like to use the slider.
I've not been able to make the slider appear in the browser. That is, you can see that it is there in developer tools (as far as the html is concerned, there is an element there), but you can't actually see it on the page. Trying to change its style by e.g. making it wider affects the style attributes of the html element in the developer tools, but on the page is still says that it's 0x0 pixels (and you still can't see it).
I thought that this problem might be because of clashes with other libraries in my app, or perhaps with other elements on the page, so I made a new Meteor project to try a minimal example. I had the same problem - the slider didn't appear. Then I thought that maybe it was Meteor that was the problem, so I made a super-minimal example using only plain React, not even any JSX to avoid having to use any build system (as per this article: [https://shinglyu.github.io/web/2016/04/06/minimal_react.html](url)). Still the same problem.

EDIT: We have made a few small changes to the code since the initial post. It is still not working.

This is the html file:
```
<head>
    <title>Slider</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/react-rangeslider@2.1.0/umd/randeslider.min.css" />
</head>

<body>
    <div id="content"></div>
    
    <script src="https://fb.me/react-0.14.7.js"></script>
    <script src="https://fb.me/react-dom-0.14.7.js"></script>
    <script src="https://unpkg.com/react-rangeslider/umd/rangeslider.min.js"></script>
    <script src="purereact.js"></script>
</body>
```

This is the javascript file (`purereact.js`):
```
var h = React.createElement

// from the demo provided in the readme
class VolumeSlider extends React.Component {
  constructor(props, context) {
    super(props, context)
    this.state = {
      volume: 0
    }
  }

  handleOnChange(value) {
    this.setState({
      volume: value
    })
  }

  render() {
    let { volume } = this.state
    return (
      h('window.ReactRangeslider.default', {value: this.state.volume, min: 0, max: 100, orientation: "vertical", onChange: this.handleOnChange}, null)
    )
  }
}

ReactDOM.render(h('div', null, 
                  h('VolumeSlider', {min: 10, max: 100})   
                 ), document.getElementById('content'))
```

I've tried it using Chrome version 58.0.3029.110 and Safari version 9.0.3.

**Comment by vladbalan** [comment]
+1

@bigstas I'm having the same issue. Did you manage to get it working?

**Comment by inPhoenix** [comment]
Did you import `'react-rangeslider/lib/index.css'` ?

**Comment by bigstas** [comment]
@inPhoenix : I tried this now, see the above updated code. It still does the same as before.

**Comment by inPhoenix** [comment]
@bigstas: Please check this example and see if it helps: 
https://inphoenix.github.io/inRangeSlider/

**Comment by whoisandy** [comment]
@bigstas Please check out https://codesandbox.io/s/6z992xq4mr.
