### ISSUE TITLE
Mouse move outside of window while dragging causes error

### ISSUE THREAD

**Issue by kaufmo** [whoisandy/react-rangeslider#71]
Hello,
do you know the problem when you drag the handle and move the mouse outside of the window?

The error comes from the handleDrag function, because target changes to document dom element and there is no classList option. I think this will be solved when you check if target has the attribute classList?

Best regards,
Alex

**Comment by tomay** [comment]
Is it this error you are referring to? 
```
Uncaught TypeError: Cannot read property 'contains' of undefined
    at HTMLDocument.Slider._this.handleDrag (eval at <anonymous> (bundle.js:4), <anonymous>:111:27)
```

I get these even on the demo page:
https://whoisandy.github.io/react-rangeslider/

**Comment by kaufmo** [comment]
yes it's the same error
