### ISSUE TITLE
Increase space between slider and labels

### ISSUE THREAD

**Issue by jzillmann** [whoisandy/react-rangeslider#78]
Following code:
```
<Slider
                             min={ 0 }
                             max={ 50 }
                             value={ value }
                             step={ 5 }
                             onChange={ this.changeValue.bind(this) }
                             labels={ { 0: '0%', 5: '5%', 10: '10%', 20: '20%', 50: '50%' } }
                             format={ (value) => value + '%' } />
```

produces the following slider:
<img width="655" alt="slider" src="https://user-images.githubusercontent.com/148472/29808691-706b20d6-8c99-11e7-845b-4be499cf85f9.png">

It can be seen live at http://jmh.morethan.io/#twoRunsExample

Now the question... How can i increase the space between slider and labels? It looks a bit off in case the slider knob is at a label...

**Comment by StefanFeser** [comment]
Hi @jzillmann 
You can easily increase the space between slider and labels by changing the `top` CSS property:
```
.rangeslider__label-list .rangeslider__label {
  position: absolute;
  font-size: 14px;
  cursor: pointer;
  display: inline-block;
  top: 35px; // change this property
}
```

**Comment by jzillmann** [comment]
@StefanFeser Thanks, works like a charm!
